apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  application.yml: |
    demo:
      message: Welcome to Spring Boot on Kubernetes!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s
    wavefront:
      application:
        name: incontro-devops
        service: ${spring.application.name}
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      metrics:
        tags:
          application: ${spring.application.name}
        export:
          wavefront:
            enabled: true
            uri: https://longboard.wavefront.com
